### ISSUE TITLE
Fix PHPMailer

### ISSUE THREAD

**Issue by MacRichards** [OAWest/western.oa-bsa.org#120]
It was brought to my attention that our Contact Us page no longer works. After you click the submit button it will give you this error message in the iframe.

> Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by blove** [comment]
@MacRichards are you able to troubleshoot this issue? I think we are using a gmail account, so perhaps we should check that the smtp settings are still correct and that we did not change the credentials.

We switched to using a gmail account due to the national server being blocked by Microsoft for sending emails. I believe this has been resolved, so we could ditch PHPMailer and go back to using the mail() function to send the emails.

**Comment by MacRichards** [comment]
@blove I can't find the PHPMailer files on our website. Did they get deleted accidentally or am I not looking in the right place?

**Comment by InfamousStarFox** [comment]
@MacRichards Due to security, we are not storing the PHPMailer files on Github. You will need to connect via FTP to the website, and then navigate to /home/western/public_html/PHPMailer

**Comment by MacRichards** [comment]
@blove @InfamousStarFox I do not have FTP access.

**Comment by blove** [comment]
@MacRichards I just send you an email with the details.

**Comment by InfamousStarFox** [comment]
I have updated the server to use the default mail function instead of PHPMailer
